/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hiratak' at '12/3/16 3:04 AM' with Gradle 3.1
 *
 * @author hiratak, @date 12/3/16 3:04 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
